import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
// import { Sidebar } from "@/components/sidebar/Sidebar";
// import { SWRProvider } from "./swr-provider";
import { sora } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SWRProvider>
    <html lang="fr">
      <body className={sora.className}>
        <div className="main-container">
          <div className="main-navbar">
            <Navbar />
          </div>
          <div className="main-content">{children}</div>
        </div>
      </body>
    </html>
    // </SWRProvider>
  );
}
